"""empty message

Revision ID: e601a58b4fec
Revises: 920089af3546
Create Date: 2020-07-27 19:33:01.833634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e601a58b4fec'
down_revision = '920089af3546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('values', 'value',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('values', 'value',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
